---
  record:
    load_dir: /hdd/datasets/object_data/igibson/run
    save_dir: /hdd/datasets/object_data/igibson/run
    refresh: True
  environment:
    env: iGibson
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action proprioception
    load_rollouts: /hdd/datasets/object_data/igibson/random
    num_frames: 10000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.001
...