---
  record:
    load_dir: /hdd/datasets/object_data/igibson/run
    save_dir: /hdd/datasets/object_data/igibson/run
    refresh: False
  environment:
    env: iGibson
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: proprioception Action peach_62_multiplexer
    load_rollouts: /hdd/datasets/object_data/igibson/run/proprioception/
    num_frames: 100000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.1
    num_samples: 60
    sample_grid: False
    dynamics_difference: True
...