---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/default/raw/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/raw/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/raw/default/
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random/
    num_iters: 10000
    batch_size: 64
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    load_intermediate: /hdd/datasets/object_data/full/randomdist/raw/temp/
    # save_intermediate: /hdd/datasets/object_data/full/randomdist/raw/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      # passive_iters: 10000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      # weighting: 0 200000 100 100000
      # intrain_passive: True
  full_inter:
    object_id: True
    lasso_lambda: 5 0.0 0.0 0 0
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    lightweight_passive: False
    train_names: vgqccm
  interaction_net:
    net_type: rawattn
    activation: leakyrelu
    init_form: xuni
    pair:
      final_layers: 128
      repeat_layers: True
    # embed_inputs: 32
    mask_attn:
      model_dim: 128
      num_heads: 16
      num_layers: 4
      cluster: False
      num_clusters: 0
      attention_dropout: 0.1
      gumbel_temperature: 2
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00000
...