---
  record:
    record_rollouts: ""
    record_recycle: -1
    # load_dir: /hdd/datasets/hype/robopushing/testrun/
    save_dir: /hdd/datasets/hype/robopushing/testrun
  environment:
    env: RoboPushing
    variant: discrete
  arg_dict: hype
  train_mode: reward # either reward or policy
  train_edge: Action Gripper
  reward:
    champ_parameters: 3 5 1 100 100 2 .01 3 # Ball: [15, 10, 1, 100, 100, 2, 1e-2, 3] 
    dp_gmm: 10 6000 100 diag 1e-10
    use_changepoint: False
    proximity: -1
    num_frames: 1500
    reward_base: -1
    param_reward: 1
    load_rollouts: /hdd/datasets/object_data/robopushing/discrete/random
    min_size: 100
...