---
  record:
    record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/breakout/testrun/
    save_dir: /hdd/datasets/hype/robopushing/testrun
  environment:
    env: RoboPushing
    variant: discrete
  arg_dict: hype
  train_mode: reward # either reward or policy
  train_edge: Gripper Block
  reward:
    champ_parameters: 15 10 1 100 100 2 1e-2 3 
    dp_gmm: 10 6000 100 diag 1e-10
    use_changepoint: False
    proximity: 0.05
    num_frames: 50000
    reward_base: -0.1
    param_reward: 2
    load_rollouts: /hdd/datasets/hype/robopushing/Gripper/
    # one_mode: True
    # min_size: 20
...