---
metaparam: 
  multi_filename: inter_pusher2d_trials2_
  log_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_logs/inter_pusher2d_trials2/
  yaml_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_yamls/inter_pusher2d_trials2/
  save_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam/inter_pusher2d_trials2/
  graph_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_graphs/inter_pusher2d_trials2/
  bash_path: bashes/inter_pusher2d_trials2.sh
  base_config: configs/full_training/Pusher2D/base.yaml
  runfile: train_full_interaction.py
  gpu: 0
  match: 0
  simul_run: 12
  num_trials: 6
  cycle_gpu: 4
full_inter:
  adaptive_lasso: 1 1,2 1,5 1
...