---
metaparam: 
  multi_filename: inter_pusher2d_tests_
  log_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_logs/inter_pusher2d_tests/
  yaml_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_yamls/inter_pusher2d_tests/
  save_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam/inter_pusher2d_tests/
  graph_endpoint: /data/calebc/object_data/full/hyperparam/hyperparam_graphs/inter_pusher2d_tests/
  bash_path: bashes/inter_pusher2d_tests.sh
  base_config: configs/full_training/Pusher2D/base.yaml
  runfile: train_full_interaction.py
  gpu: 0
  match: 0
  simul_run: 8
  num_trials: 1
  cycle_gpu: 4
train:
  batch_size: 128,256,512,1024
inter:
  predict_dynamics: True,False
  passive:
    passive_iters: 0,1000,2000,5000,10000
    pretrain_active: True,False
  active:
    interaction_schedule: -1,0.1,0.2,0.5,0.7,0.9,1000,5000,10000,25000,50000
    intrain_passive: 1,0
    weighting: 0 0 -1 -1,0 200000 1 -1,0 200000 2 -1,0 200000 3 -1,0 200000 1 20000
full_inter:
  mixed_interaction: mixed,relaxed
  use_active_as_passive: True,False
  adaptive_lasso: 1 1,2 1,3 1,4 1,5 1,6 1,7 1,8 1,9 1,10 1,4 2,5 2,6 2,4 3,5 3,6 3
  adaptive_lasso_type: mean,meanvar
  cap_probability: 0.0,0.0001,0.001,0.01,0.02,0.03
interaction_net:
  hidden_sizes: 512 512,512,256 256,128,128 128 128 128 128,128 128 128 128,128 128 128,128 128,128
  activation: leakyrelu,sin,prelu,sinc,sigmoid,tanh,crelu
  init_form: uni,orth,xnorm,xuni,knorm,kuni
  pair:
    reduce_function: sum,max
    pre_dropout: 0.0,0.1,0.2,0.3
  embed_inputs: 256,512,1024
  optimizer:
    lr: .001,.0001,.00001
    alt_lr: .001,.0005,.0001,.00005,.00002,.00001,.000005
    weight_decay: 0.001,0.0001,0.00001,0.0
...