---
metaparam: 
  multi_filename: dag_1_rare_tests_
  log_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_logs/dag_1_rare_tests/
  yaml_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_yamls/dag_1_rare_tests/
  save_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam/dag_1_rare_tests/
  graph_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_graphs/dag_1_rare_tests/
  bash_path: bashes/dag_1_rare_tests.sh
  base_config: configs/full_training/DAG/1_rare/base.yaml
  runfile: train_full_interaction.py
  gpu: 0
  match: 0
  simul_run: 4
  num_trials: 5
  cycle_gpu: 1
# train:
#   batch_size: 128,256,512
# inter:
#   # predict_dynamics: True
#   passive:
#     passive_iters: 0,1000,2000,5000,10000
#     pretrain_active: True,False
#   active:
#     interaction_schedule: 0,1000,5000,10000,25000,50000
#     intrain_passive: 1,0
full_inter:
#   mixed_interaction: mixed,relaxed
#   use_active_as_passive: True,False
  adaptive_lasso: 1 1,5 1,7 1,10 1
inter:
  active:
    weighting: 0 200000 1 -1,0 200000 2 -1,0 200000 3 -1,0 200000 1 20000
# interaction_net:
#   hidden_sizes: 512 512,512,256 256,128,128 128 128 128 128,128 128 128 128,128 128 128,128 128,128
#   activation: leakyrelu,sin,prelu,sinc,sigmoid,tanh
#   init_form: uni,orth,xnorm,xuni,knorm,kuni
#   pair:
#     reduce_function: sum,max
  # embed_inputs: 512
#   optimizer:
#     lr: .001,.0001,.00001
#     alt_lr: .001,.0005,.0001,.00005,.00001,.000005
#     weight_decay: 0.001,0.0001,0.00001,0.0
...