metaparam: 
  multi_filename: dag_3_c_small_trials_
  log_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_logs/dag_3_c_small_trials/
  yaml_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_yamls/dag_3_c_small_trials/
  save_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam/dag_3_c_small_trials/
  graph_endpoint: /hdd/datasets/object_data/full/hyperparam/hyperparam_graphs/dag_3_c_small_trials/
  bash_path: bashes/dag_3_c_small_trials.sh
  base_config: configs/full_training/DAG/3_chain/3_c_small.yaml
  runfile: train_full_interaction.py
  gpu: 2
  match: 0
  simul_run: 5
  num_trials: 5
  cycle_gpu: 0
train:
  batch_size: 512
