---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/attn_hot/default/weighted/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/small/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/attn_hot/default/weighted
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random/
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    # num_frames: 100
    num_frames: 10000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random/
    num_iters: 10000
    # batch_size: 2
    batch_size: 128
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/exp/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/exp/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 2000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_steps: 100
      active_log_interval: 1
      # inline_iters: 10 0 5000
      inline_iters: 30 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 10000
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1 0 0.5 5 10
    mixed_interaction: mixed
    soft_distribution: Identity
    # use_active_as_passive: True
  interaction_net:
    hidden_sizes: 512 256 128 128
    net_type: keypair
    init_form: xnorm
    pair:
      final_layers: 256
      num_pair_layers: 1
      repeat_layers: True
    embed_inputs: 128
    cluster:
      cluster_mode: True
      inter_pair_layers: 1
      num_clusters: 3
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00001
...