---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /hdd/datasets/object_data/full/DAG/2_in/attn/log/inter.log
    # load_dir: /hdd/datasets/object_data/full/DAG/2_in/testrun/
    save_dir: /hdd/datasets/object_data/full/DAG/2_in/attn/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/2_in/attn/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/DAG/2_in/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/DAG/2_in/attn/
  environment:
    env: RandomDAG
    variant: 2-in
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/2_in/
    load_environment: /hdd/datasets/object_data/RandomDAG/2_in/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/2_in/
    load_rollouts: /hdd/datasets/object_data/RandomDAG/2_in/
    num_iters: 50000
    batch_size: 512
  collect:
    omit_done: True
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/DAG/2_in/attn/temp/
    save_intermediate: /hdd/datasets/object_data/full/DAG/2_in/attn/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 2000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 200
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 10000
      # weighting: 0 200000 100 100000
      intrain_passive: 1
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: $C
    predict_next_state: False
    adaptive_lasso: 1 1
  interaction_net:
    hidden_sizes: 512
    net_type: maskattn
    init_form: xnorm
    embed_inputs: 512
    activation: crelu
    pair:
      repeat_layers: True
      final_layers: 512
    mask_attn:
      model_dim: 256
      num_heads: 16
      num_layers: 2
      cluster: False
      num_clusters: 0
      attention_dropout: 0.1
      merge_function: sum
      mask_mode: query
      gumbel_attention: -1
      append_keys: True
      no_hidden: True
    optimizer:
      lr: .0001
      alt_lr: .00002
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...