---
metaparam: 
  multi_filename: ride_variant_runs
  log_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_logs/ride_variant/
  yaml_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_yamls/ride_variant/
  save_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam/ride_variant/
  graph_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_graphs/ride_variant/
  bash_path: bashes/ride_variant_runs.sh
  base_config: configs/Baselines/RIDE/breakout/ride.yaml
  runfile: train_baselines.py
  gpu: 0
  simul_run: 4
  match: 0
  num_trials: 8
  cycle_gpu: 4
environment:
  variant: big_block,single_block,negative_rand_row,center_medium,harden_single,proximity 
...