---
metaparam: 
  multi_filename: ride_runs3
  log_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_logs/ride3/
  yaml_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_yamls/ride3/
  save_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam/ride3/
  graph_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_graphs/ride3/
  bash_path: ride_runs3.sh
  base_config: configs/Baselines/RIDE/breakout/ride.yaml
  runfile: train_baselines.py
  gpu: 0
  simul_run: 8
  match: 0
  num_trials: 8
  cycle_gpu: 4
environment:
  variant: default 
...