---
metaparam: 
  multi_filename: ride_runs
  log_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_logs/ride/inter/
  yaml_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_yamls/ride/inter/
  save_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam/ride/inter/
  graph_endpoint: /nfs/data/object_data/baselines/breakout/hyperparam/hyperparam_graphs/ride/inter/
  bash_path: ride_runs.sh
  base_config: configs/Baselines/RIDE/breakout/ride.yaml
  runfile: train_interaction.py
  gpu: 0
  simul_run: 4
  match: 0
  num_trials: 8
  cycle_gpu: 4
environment:
  variant: drop_stopping 
...