python create_config_sweep.py configs/Asteroids/meta/ship_gamma_meta.yaml
python create_config_sweep.py configs/Asteroids/meta/ship_lr_meta.yaml
python create_config_sweep.py configs/Asteroids/meta/ship_network_meta.yaml
python create_config_sweep.py configs/Asteroids/meta/ship_pri_meta.yaml
python create_config_sweep.py configs/Asteroids/meta/ship_tc_meta.yaml
python create_config_sweep.py configs/Sokoban/meta/pusher_gamma_meta.yaml 
python create_config_sweep.py configs/Sokoban/meta/pusher_lr_meta.yaml 
python create_config_sweep.py configs/Sokoban/meta/pusher_network_meta.yaml 
python create_config_sweep.py configs/Sokoban/meta/pusher_pri_meta.yaml 
python create_config_sweep.py configs/Sokoban/meta/pusher_tc_meta.yaml