---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /hdd/datasets/object_data/full/DAG/3_c_small/base/log/inter.log
    # load_dir: /hdd/datasets/object_data/full/DAG/3_c_small/testrun/
    save_dir: /hdd/datasets/object_data/full/DAG/3_c_small/base/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/3_c_small/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/DAG/3_c_small/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/DAG/3_c_small/base/
  environment:
    env: RandomDAG
    variant: 3-c-small
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/3_c_small/
    load_environment: /hdd/datasets/object_data/RandomDAG/3_c_small/
  torch:
    gpu: 1
    no_cuda: False
  collect:
    omit_done: True
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/3_c_small/
    load_rollouts: /hdd/datasets/object_data/RandomDAG/3_c_small/
    num_iters: 150000
    batch_size: 512
  inter:
    predict_dynamics: False
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/DAG/3_c_small/base/temp/
    # save_intermediate: /hdd/datasets/object_data/full/DAG/3_c_small/base/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 2000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 200
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 5000
      # weighting: 0 200000 100 100000
      intrain_passive: 1
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: $C
    predict_next_state: False
    adaptive_lasso: 7 1
  interaction_net:
    hidden_sizes: 512 512 512 512 512
    net_type: keypair
    init_form: xnorm
    embed_inputs: 512
    activation: crelu
    pair:
      reduce_function: sum
      num_pair_layers: 1
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.000
...