---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /hdd/datasets/object_data/full/randomdist/default/mixed/log/inter.log
    # load_dir: /hdd/datasets/object_data/full/breakout/mixed/testrun/
    save_dir: /hdd/datasets/object_data/full/randomdist/mixed/default/
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_test/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 10000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_test/
    num_iters: 2000
    batch_size: 256
    # batch_size: 1
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/mixed/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/mixed/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 1000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      # weighting: 0 200000 100 100000
      intrain_passive: True
  full_inter:
    object_id: True
    lasso_lambda: 3 0.0 0.0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    train_names: ogzncsrsf
    adaptive_lasso: 3
    use_active_as_passive: True
  interaction_net:
    hidden_sizes: 128 256
    net_type: keypair
    init_form: xnorm
    embed_inputs: 128
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...