---
  record:
    # record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/full/breakout/small/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/zero_passive/
  environment:
    env: RandomDistribution
    variant: zero_passive
    load_environment: /hdd/datasets/object_data/full/randomdist/zero_passive/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    train_edge: Paddle Ball
    load_rollouts: /hdd/datasets/object_data/full/randomdist/zero_passive/
    num_iters: 50000
    batch_size: 256
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/zero_passive/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 1 # 20000
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 500
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 1000
      weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1
  interaction_net:
    hidden_sizes: 512 256 256 128 128
    net_type: keypair
    init_form: xnorm
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.01
...