---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/default/embed/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/embed/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/embed/default/
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 200000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
    num_iters: 30000
    batch_size: 128
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/embed/gradient/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/embed/gradient/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 10000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_steps: 1
      active_log_interval: 25
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      # intrain_passive: True
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1 0 0 0 0
    dist_temperature: 1
    mixed_interaction: mixed
    soft_distribution: Identity
    # use_active_as_passive: True
    log_gradients: True
    # train_full_only: True
    train_names: phpt
  interaction_net:
    # hidden_sizes: 128
    net_type: maskattn
    init_form: xnorm # -1 dim is num_queries
    pair:
      final_layers: 256 256 256
      repeat_layers: True
    mask_attn:
      # model_dim: 5 # 128
      # num_heads: 6 # 16
      model_dim: 128
      num_heads: 16
      num_layers: 3
      cluster: False
      num_clusters: 0
      attention_dropout: 0.1
      merge_function: max
      append_keys: True
    optimizer:
      lr: .00001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.000
...