---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/default/log/experiment1/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/relaxed/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/base/experiment1/
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random/
    # load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 200000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random/
    # load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional
    num_iters: 2000
    batch_size: 256
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/exp1/cond/temp/
    # save_intermediate: /hdd/datasets/object_data/full/randomdist/exp1/cond/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 10000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_steps: 30
      active_log_interval: 5
      # inline_iters: 10 0 5000
      inline_iters: 30 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 10
      # intrain_passive: True
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1 1 0 10 0
    dist_temperature: 1
    mixed_interaction: mixed
    soft_distribution: Identity
    # use_active_as_passive: True
    log_gradients: True
    # train_full_only: True
    # train_names: gscfagrs
    # dual_lasso: 1 30
  interaction_net:
    hidden_sizes: 256 256
    embed_inputs: 512
    net_type: keypair
    init_form: xnorm
    optimizer:
      lr: .00001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...