---
metaparam: 
  multi_filename: big_runs_
  log_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_logs/big_runs/test/
  yaml_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_yamls/big_runs/test/
  save_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam/big_runs/test/
  graph_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_graphs/big_runs/test/
  bash_path: big_runs.sh
  base_config: configs/Baselines/HyPE/Breakout/big_block_hype.yaml
  runfile: train_baselines.py
  gpu: 0
  match: 0
  simul_run: 5
  num_trials: 5
  cycle_gpu: 4
skill:
  num_iters: 5000
...