---
metaparam: 
  multi_filename: neg_runs_
  log_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_logs/neg_runs/test/
  yaml_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_yamls/neg_runs/test/
  save_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam/neg_runs/test/
  graph_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_graphs/neg_runs/test/
  bash_path: neg_runs.sh
  base_config: configs/Baselines/HyPE/Breakout/neg_hype.yaml
  runfile: train_baselines.py
  gpu: 3
  match: 0
  simul_run: 5
  num_trials: 5
  cycle_gpu: 4
skill:
  num_iters: 10000
...