---
metaparam: 
  multi_filename: prox_runs_
  log_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_logs/prox_runs/test/
  yaml_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_yamls/prox_runs/test/
  save_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam/prox_runs/test/
  graph_endpoint: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam_graphs/prox_runs/test/
  bash_path: prox_runs.sh
  base_config: configs/Baselines/HyPE/Breakout/prox_hype.yaml
  runfile: train_baselines.py
  gpu: 1
  match: 0
  simul_run: 5
  num_trials: 5
  cycle_gpu: 4
skill:
  num_iters: 10000
...