---
  record:
    record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/breakout/testrun/
    save_dir: /hdd/datasets/hype/breakout/testrun
  environment:
    env: Breakout
  arg_dict: hype
  train_mode: reward # either reward or policy
  train_edge: Paddle Ball
  reward:
    champ_parameters: 15 10 1 100 100 2 1e-2 3 
    dp_gmm: 10 6000 100 diag 1e-10
    use_changepoint: True
    proximity: 8
    num_frames: 25000
    reward_base: 0
    param_reward: 200
    load_rollouts: /hdd/datasets/hype/breakout/Paddle
    one_mode: True
    min_size: 20
...