---
record:
  # record_rollouts: /hdd/datasets/hype/breakout/Paddle/
  record_recycle: -1
  load_dir: /nfs/data/calebc/hype/breakout/testrun/
  save_interval: 10
  # save_dir: /hdd/datasets/hype/breakout/testrun/
environment:
  env: Breakout
  variant: drop_stopping
arg_dict: hype
train_mode: skill # either reward or policy
train_edge: Paddle Ball
reward:
  reward_base: -.01
  param_reward: 10.0
  changepoint_reward: 0
  one_mode: True
skill:
  temporal_extend: 2
  policy_iters: 100
  policy_iters_schedule: 15
  # num_repeats_schedule: 1
  obs_components: 0 0 1
  num_iters: 400
  num_repeats: 10
  buffer_len: 50000
  normalized: False
  # input_scaling: 25
  train_log_maxlen: 15
  test_trials: 3
  log_interval: 1
  epsilon_random: 0.0
  num_networks: 10
  learning_type: cmaes
  learn:
    init_var: 0.2
    grad_epoch: 1
    discount_factor: 0.0
    elitism: 2
critic_net:
actor_net:
network:
  hidden_sizes: 128
  net_type: mlp
  # activation_final: tanh
  # activation: sinc
  activation: relu
  # scale_logits: 10
  # scale_final: 10
  init_form: xnorm
  optimizer:
    lr: .0001
    alt_lr: .0001
    eps: .00001
    alpha: 0.99
    betas: 0.9 0.999
    weight_decay: 0.00
...