---
record:
  # record_rollouts: /hdd/datasets/hype/breakout/Paddle/
  record_recycle: -1
  load_dir: /nfs/data/calebc/object_data/hype/hyperparam/hyperparam/ball_grad_trains/test/ball_grad_trains_9_trial_0
  # 2,3 are best right now
  # save_dir: /hdd/datasets/hype/breakout/testrun/
  save_interval: 100
environment:
  env: Breakout
  variant: drop_stopping
arg_dict: hype
train_mode: test # either reward or policy
train_edge: Paddle Ball
reward:
  true_reward: False
skill:
  log_interval: 50
  train_log_maxlen: 100
  num_iters: 3000
  test_policy_iters: 100
  test_trials: 10
...