---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/conditional/embed/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/embed/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/conditional/embed/
  environment:
    env: RandomDistribution
    variant: conditional
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
    num_iters: 10000
    batch_size: 128
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/mixed/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/mixed/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 5000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      # weighting: 0 200000 100 100000
      intrain_passive: True
  full_inter:
    object_id: True
    lasso_lambda: 2 0.5 0.0 100 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
  interaction_net:
    hidden_sizes: 256 256 256
    net_type: keyembed
    init_form: xnorm
    embed_inputs: 1024
    activation: leakyrelu
    pair:
      reduce_function: max
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.0001
...