---
  debug:
    run_test: action
    collect_mode: False
  record:
    load_dir: /nfs/data/calebc/object_data/breakout/testrun/
  environment:
    env: Breakout
    demonstrate: True
  train:
    train: True
    train_edge: Action Paddle
...