---
  debug:
    run_test: logging
    collect_mode: False
  record:
    load_dir: /nfs/data/calebc/object_data/breakout/testrun/
  environment:
    env: Breakout
    variant: drop_stopping
    demonstrate: True
  train:
    pretrain_frames: 100
    train: True
    num_steps: 100
    num_iters: 10
    train_edge: Action Paddle
  critic_net:
  actor_net:
  network:
    hidden_sizes: 128 128 128
  extract:
    single_obs_setting: 1 0 0 1 0 0
    relative_obs_setting: 0 0 0 1
  policy:
    sample_form: merged
    logging:
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 5
      test_trials: 10
  hindsight:
    use_her: True
...