---
metaparam: 
  multi_filename: pusher_option_
  log_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_logs/pusher/pri2/
  yaml_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_yamls/pusher/pri2/
  save_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam/pusher/pri2/
  graph_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_graphs/pusher/pri2/
  bash_path: pusher_pri2.sh
  base_config: configs/Sokoban/few_obs/action_pusher_option.yaml
  runfile: train_option.py
  gpu: 2
  match: False
policy:
  primacy:
    reset_layers: 2,3
    reset_frequency: 200
    primacy_iters: 40
  lookahead: 2,5,10
...
