---
metaparam: 
  multi_filename: pusher_option_
  log_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_logs/pusher/gamma2/
  yaml_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_yamls/pusher/gamma2/
  save_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam/pusher/gamma2/
  graph_endpoint: /hdd/datasets/object_data/sokoban/few_obs/hyperparam/hyperparam_graphs/pusher/gamma2/
  bash_path: pusher_gamma2.sh
  base_config: configs/Sokoban/few_obs/action_pusher_option.yaml
  runfile: train_option.py
  gpu: 3
  match: False
option:
  constant_lambda: -0.1,-1,-2
  param_lambda: 1,5
policy:
  discount_factor: 0.99,0.9
...
