---
metaparam: 
  multi_filename: attn_cond_tests_
  log_endpoint: /work/pi_sniekum_umass_edu/calebc/object_data/full/hyperparam/hyperparam_logs/attn_cond_tests/
  yaml_endpoint: /work/pi_sniekum_umass_edu/calebc/object_data/full/hyperparam/hyperparam_yamls/attn_cond_tests/
  save_endpoint: /work/pi_sniekum_umass_edu/calebc/object_data/full/hyperparam/hyperparam/attn_cond_tests/
  graph_endpoint: /work/pi_sniekum_umass_edu/calebc/object_data/full/hyperparam/hyperparam_graphs/attn_cond_tests/
  bash_path: bashes/attn_cond_tests.sh
  base_config: configs/full_training/RandomDistribution/conditional/attention/full_random_conditional_relaxed_attn.yaml
  runfile: train_full_interaction.py
  gpu: 0
  match: 0
  simul_run: 8
  num_trials: 1
  cycle_gpu: 1
train:
  batch_size: 128,256,512
inter:
  # predict_dynamics: True
  passive:
    passive_iters: 0,1000,2000,5000,10000
    pretrain_active: True,False
  active:
    interaction_schedule: 0,1000,5000,10000,25000,50000
    intrain_passive: 1,0
full_inter:
  mixed_interaction: mixed,relaxed
  use_active_as_passive: True,False
  adaptive_lasso: 0.1,0.5,0.75,1,2,3,4,5,6,7,8,9,10
interaction_net:
  hidden_sizes: 512,256,128,128 128 128 128 128,128 128 128 128
  activation: leakyrelu,sin,prelu,sinc,sigmoid,tanh
  init_form: uni,orth,xnorm,xuni,knorm,kuni
  net_type: parattn,maskattn
  pair:
    final_layers: 128,128 128,128 128 128,256 256
  embed_inputs: 512,256,128,64,32
  optimizer:
    lr: .001,.0001,.00001
    alt_lr: .001,.0005,.0001,.00005,.00001,.000005
    weight_decay: 0.001,0.0001,0.00001,0.0
  mask_attn:
    model_dim: 32,64,128,256,512
    num_heads: 4,8,16,32,64
    num_layers: 1,2,3
    attention_dropout: 0.0,0.1,0.2,0.3,0.4
    merge_function: sum,max,cat
    append_keys: True,False
    no_hidden: True,False
...