---
metaparam: 
  multi_filename: attn_1_hdim_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/attn_1_hdim/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/attn_1_hdim/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/attn_1_hdim/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/attn_1_hdim/
  bash_path: bashes/attn_1_hdim.sh
  base_config: configs/ac_baselines/DAG/1_hdim/attn.yaml
  runfile: train_full_baselines.py
  gpu: 2
  match: 0
  simul_run: 2
  num_trials: 5
  cycle_gpu: 4
inter_baselines:
  attention_threshold: 0.3333
...