---
metaparam: 
  multi_filename: attn_1_in_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/attn_1_in/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/attn_1_in/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/attn_1_in/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/attn_1_in/
  bash_path: bashes/attn_1_in.sh
  base_config: configs/ac_baselines/DAG/1_in/attn.yaml
  runfile: train_full_baselines.py
  gpu: 2
  match: 0
  simul_run: 2
  num_trials: 10
  cycle_gpu: 0
inter_baselines:
  attention_threshold: 0.5
...