---
metaparam: 
  multi_filename: cfact_1_rare_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/cfact_1_rare/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/cfact_1_rare/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/cfact_1_rare/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/cfact_1_rare/
  bash_path: bashes/cfact_1_rare.sh
  base_config: configs/ac_baselines/DAG/1_rare/cfact.yaml
  runfile: train_full_baselines.py
  gpu: 3
  match: 0
  simul_run: 3
  num_trials: 5
  cycle_gpu: 4
inter_baselines:
  counterfactual_threshold: 0.1
...