---
metaparam: 
  multi_filename: cfact_push_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/cfact_push/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/cfact_push/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/cfact_push/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/cfact_push/
  bash_path: bashes/cfact_push.sh
  base_config: configs/ac_baselines/DAG/Pusher2D/cfact.yaml
  runfile: train_full_baselines.py
  gpu: 3
  match: 0
  simul_run: 3
  num_trials: 10
  cycle_gpu: 0
inter_baselines:
  counterfactual_threshold: 137
...