---
metaparam: 
  multi_filename: cfact_break_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/cfact_break/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/cfact_break/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/cfact_break/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/cfact_break/
  bash_path: bashes/cfact_break.sh
  base_config: configs/ac_baselines/DAG/Breakout/cfact.yaml
  runfile: train_full_baselines.py
  gpu: 3
  match: 0
  simul_run: 3
  num_trials: 5
  cycle_gpu: 0
inter_baselines:
  counterfactual_threshold: 137
...