---
metaparam: 
  multi_filename: grad_3_in_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/grad_3_in/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/grad_3_in/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/grad_3_in/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/grad_3_in/
  bash_path: bashes/grad_3_in.sh
  base_config: configs/ac_baselines/DAG/3_in/grad.yaml
  runfile: train_full_baselines.py
  gpu: 1
  match: 0
  simul_run: 3
  num_trials: 10
  cycle_gpu: 0
inter_baselines:
  gradient_threshold: 0.04
...