---
metaparam: 
  multi_filename: grad_3_chain_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/grad_3_chain/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/grad_3_chain/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/grad_3_chain/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/grad_3_chain/
  bash_path: bashes/grad_3_chain.sh
  base_config: configs/ac_baselines/DAG/3_chain/grad.yaml
  runfile: train_full_baselines.py
  gpu: 1
  match: 0
  simul_run: 3
  num_trials: 10
  cycle_gpu: 0
inter_baselines:
  gradient_threshold: 0.1,0.15,0.2,0.25,0.3
...