---
metaparam: 
  multi_filename: grad_1_rare_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/grad_1_rare/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/grad_1_rare/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/grad_1_rare/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/grad_1_rare/
  bash_path: bashes/grad_1_rare.sh
  base_config: configs/ac_baselines/DAG/1_rare/grad.yaml
  runfile: train_full_baselines.py
  gpu: 1
  match: 0
  simul_run: 3
  num_trials: 5
  cycle_gpu: 0
inter_baselines:
  gradient_threshold: 0.3
...