---
metaparam: 
  multi_filename: grad_multi_in_
  log_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_logs/grad_multi_in/
  yaml_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_yamls/grad_multi_in/
  save_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam/grad_multi_in/
  graph_endpoint: /hdd/datasets/object_data/ac_base/hyperparam/hyperparam_graphs/grad_multi_in/
  bash_path: bashes/grad_multi_in.sh
  base_config: configs/ac_baselines/DAG/multi_in/grad.yaml
  runfile: train_full_baselines.py
  gpu: 1
  match: 0
  simul_run: 3
  num_trials: 10
  cycle_gpu: 0
inter_baselines:
  gradient_threshold: 0.1,0.15,0.2,0.25,0.3,0.35
...