---
metaparam: 
  multi_filename: ball_option_
  log_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_logs/ball/rew/
  yaml_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_yamls/ball/rew/
  save_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam/ball/rew/
  graph_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_graphs/ball/rew/
  bash_path: ball_rew.sh
  base_config: configs/Breakout/angle_hyperparam/paddle_ball_option_inline.yaml
  runfile: train_option.py
  gpu: 1
  match: False
train:
  num_iters: 4000
option:
  param_lambda: 50,200
  true_lambda: 0,1
  trunc_true: False,True
...