---
metaparam: 
  multi_filename: ball_option_
  log_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_logs/ball/const/
  yaml_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_yamls/ball/const/
  save_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam/ball/const/
  graph_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_graphs/ball/const/
  bash_path: ball_const.sh
  base_config: configs/Breakout/angle_hyperparam/paddle_ball_option_inline.yaml
  runfile: train_option.py
  gpu: 1
  match: False
train:
  num_iters: 4000
option:
  constant_lambda: -0.1,-0.5,-1
  inter_lambda: 10,100
...