---
metaparam: 
  multi_filename: ball_option_
  log_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_logs/ball/te/
  yaml_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_yamls/ball/te/
  save_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam/ball/te/
  graph_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_graphs/ball/te/
  bash_path: ball_te.sh
  base_config: configs/Breakout/angle_hyperparam/paddle_ball_option_inline.yaml
  runfile: train_option.py
  gpu: 0
  match: False
train:
  num_iters: 4000
option:
  temporal_extend: 2,3,4
action:
  relative_action_ratio: 0.15,0.20,0.25
...