---
metaparam: 
  multi_filename: ball_option_
  log_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_logs/ball/net/
  yaml_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_yamls/ball/net/
  save_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam/ball/net/
  graph_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_graphs/ball/net/
  bash_path: ball_net.sh
  base_config: configs/Breakout/angle_hyperparam/paddle_ball_option_inline.yaml
  runfile: train_option.py
  gpu: 2
  match: False
train:
  num_iters: 4000
network:
  activation_final: tanh,none,sigmoid
  scale_logits: 10,100
  hidden_sizes: 128 128 128 128 128 128,512 512 512 512,1024 1024 1024
...