---
metaparam: 
  multi_filename: ball_inter_
  log_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_logs/ball/inter/
  yaml_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_yamls/ball/inter/
  save_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam/ball/inter/
  graph_endpoint: /hdd/datasets/object_data/breakout/hyperparam/hyperparam_graphs/ball/inter/
  bash_path: ball_inter_balldata.sh
  base_config: configs/Breakout/unit_tests/paddle_ball_interaction_test_ball.yaml
  runfile: train_interaction.py
  gpu: 0
  match: 0
  simul_run: 4
  num_trials: 1
inter:
  predict_dynamics: True,False
  interaction_testing: 0.9 -1 -13 -1,0.9 -5 -10 -1,0.9 -1 -5 -1
  active:
    inline_iters: 10 1 20000,15 1 50000,20 1 100000
    interaction_weighting: 10 -1,100 -1
    interaction_schedule: 10000,30000,100000
    weighting: 0 200000 100 100000,-10 200000 100 100000,0 200000 10 100000
    error_binary_upweight: 1,5,20,100
    intrain_passive: 0,1
interaction_net:
  hidden_sizes: 128 128 128 128 128,512 512 512,1024 1024
  net_type: mlp,inexp
  optimizer:
    lr: .0001,.00001,.000003
    alt_lr: .0001,.00001
    weight_decay: .001,.0001
...