---
  alter_base: configs/full_training/DAG/3_chain/base.yaml
  inter:
    load_intermediate: /hdd/datasets/object_data/full/DAG/3_chain_true/base/temp/
    # save_intermediate: /hdd/datasets/object_data/full/DAG/3_chain_true/base/temp/
    passive:
      passive_iters: 0
    active:
      inline_iters: 0 0 0
      train_true: True
      interaction_schedule: -1 # 5000
...