---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/all/randomdist/default/base/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/all/breakout/base/testrun/
    save_dir: /nfs/data/calebc/object_data/all/randomdist/base/default/
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_frames: 1000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional
    num_iters: 100
    batch_size: 256
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    load_intermediate: /hdd/datasets/object_data/em/randomcond/base/temp/
    # save_intermediate: /hdd/datasets/object_data/em/randomcond/base/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 0
      # passive_iters: 10000
      passive_log_interval: 100
      pretrain_active: True
    interaction:
      interaction_pretrain: 0
    active:
      active_steps: 1
      active_log_interval: 1
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      # intrain_passive: True
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1 0 0 0 0
    dist_temperature: 5
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    log_gradients: True
    # train_full_only: True
    # train_names: phpt
  interaction_net:
    hidden_sizes: 256 256 256 256
    embed_inputs: 256
    net_type: keypair
    init_form: xnorm
    optimizer:
      lr: .00001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  EMFAC:
    full_train: psxrpx
    num_masks: 3
    E_step_iters: 3000
    M_step_iters: 10
    refine_iters: 10
    binary_cost: 1

...