---
  record:
    load_dir: /nfs/data/calebc/object_data/breakout/testrun_inline/
    save_dir: /nfs/data/calebc/object_data/breakout/testrun_inline/
    refresh: True
  environment:
    env: Breakout
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action Paddle
    load_rollouts: /hdd/datasets/object_data/breakout/random
    num_frames: 1000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.05
...