---
  record:
    load_dir: /nfs/data/calebc/object_data/sokoban/no_obs/testrun/
    save_dir: /nfs/data/calebc/object_data/sokoban/no_obs/testrun/
    refresh: True
  environment:
    env: Sokoban
    variant: no_obs
  torch:
    gpu: 1
    no_cuda: False
  train:
    train_edge: Action Pusher
    load_rollouts: /hdd/datasets/object_data/sokoban/no_obs/random/
    num_frames: 1000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.04
...