---
  arg_dict: ac_base
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /hdd/datasets/object_data/base/DAG/1_in/attn/log/inter.log
    # load_dir: /hdd/datasets/object_data/base/DAG/1_in/testrun/
    save_dir: /hdd/datasets/object_data/base/DAG/1_in/attn/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/1_in/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/base/DAG/1_in/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/base/DAG/1_in/attn/
  environment:
    env: RandomDAG
    variant: 1-in
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/1_in/
    load_environment: /hdd/datasets/object_data/RandomDAG/1_in/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDAG/1_in/
    load_rollouts: /hdd/datasets/object_data/RandomDAG/1_in/
    num_iters: 100000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    # load_intermediate: /hdd/datasets/object_data/base/DAG/1_in/attn/temp/
    save_intermediate: /hdd/datasets/object_data/base/DAG/1_in/attn/temp/
    compare_trace: True
    passive:
      passive_log_interval: 100
      pretrain_active: True
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: $C
  inter_baselines:
    attention_threshold: 0.333
    attention_lambda: 100
  interaction_net:
    # hidden_sizes: 256
    net_type: parattn
    init_form: xnorm
    embed_inputs: 512
    # activation: crelu
    pair:
      repeat_layers: True
      final_layers: 256
    mask_attn:
      model_dim: 256
      num_heads: 16
      num_layers: 1
      attention_dropout: 0.1
      merge_function: sum
      mask_mode: query
      gumbel_attention: -1
      append_keys: False
      no_hidden: True
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...