---
metaparam: 
  multi_filename: attn_break_
  log_endpoint: /mnt/Data/calebc/object_data/ac_base/hyperparam/hyperparam_logs/attn_break/
  yaml_endpoint: /mnt/Data/calebc/object_data/ac_base/hyperparam/hyperparam_yamls/attn_break/
  save_endpoint: /mnt/Data/calebc/object_data/ac_base/hyperparam/hyperparam/attn_break/
  graph_endpoint: /mnt/Data/calebc/object_data/ac_base/hyperparam/hyperparam_graphs/attn_break/
  bash_path: bashes/attn_break.sh
  base_config: configs/ac_baselines/Breakout/attn.yaml
  runfile: train_full_baselines.py
  gpu: 2
  match: 0
  simul_run: 2
  num_trials: 5
  cycle_gpu: 0
inter_baselines:
  attention_threshold: 0.3333
...