---
  arg_dict: ac_base
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /mnt/Data/calebc/object_data/base/Breakout/rand_tiny/attn/log/inter.log
    # load_dir: /mnt/Data/calebc/object_data/base/Breakout/rand_tiny/testrun/
    save_dir: /mnt/Data/calebc/object_data/base/Breakout/rand_tiny/attn/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/rand_tiny/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/base/Breakout/rand_tiny/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/base/Breakout/rand_tiny/attn/
  environment:
    env: Breakout
    variant: rand_tiny
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/Breakout/rand_tiny/
    load_environment: /mnt/Data/calebc/object_data/Breakout/rand_tiny/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 500000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/Breakout/rand_tiny/
    load_rollouts: /mnt/Data/calebc/object_data/Breakout/rand_tiny/
    num_iters: 100000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    load_intermediate: /mnt/Data/calebc/object_data/baselines/Breakout/rand_tiny
    # save_intermediate: /mnt/Data/calebc/object_data/baselines/Breakout/rand_tiny
    # save_intermediate: /mnt/Data/calebc/object_data/base/Breakout/1_hdim/attn/temp/
    compare_trace: True
    passive:
      passive_log_interval: 100
      pretrain_active: True
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: $C
  inter_baselines:
    gradient_threshold: 1.0
  interaction_net:
    hidden_sizes: 256 256 256 256 256 256
    net_type: keypair
    init_form: xnorm
    embed_inputs: 1024
    activation: crelu
    pair:
      reduce_function: sum
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.000
...