---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/conditional/subset/log/model_only.log
    save_dir: /nfs/data/calebc/object_data/full/randomdist/conditional/subset_model_only
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
  torch:
    gpu: 2
    no_cuda: False
  train:
    train: True
    num_frames: 1000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
    num_iters: 5000
    batch_size: 256
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/subset/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/subset/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 100
      # passive_iters: 2000
      passive_log_interval: 100
      pretrain_active: True
    interaction:
      subset_training: 100
      interaction_pretrain: 1000
    active:
      active_log_interval: 100
      inline_iters: 1 0 0
      # inline_iters: 100 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 10000
      active_steps: 1
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 1 0 0 0 0
    use_active_as_passive: True
    # load_forward_only: /hdd/datasets/object_data/full/randomdist/conditional/temp/
    train_names: phpt
    mixed_interaction: mixed
    soft_distribution: Identity
    selection_train: softened
  interaction_net:
    hidden_sizes: 256 256 512 
    net_type: keypair
    init_form: xnorm
    embed_inputs: 128
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00001
...