---
  record:
    # record_rollouts: /hdd/datasets/object_data/minibehavior/install/testrun/ball
    # record_rollouts: /hdd/datasets/object_data/minibehavior/install/run/thaw_date
    record_recycle: -1
    log_filename: logs/temp/install_train.log
    load_dir: /hdd/datasets/object_data/minibehavior/thawing/run
    save_dir: /hdd/datasets/object_data/minibehavior/thaw_date/run/full/
    # checkpoint_dir: /nfs/data/calebc/object_data/minibehavior/install/testrun/paddle_ball_checkpoint
    save_interval: 100
  environment:
    env: MiniBehavior
    variant: thawing
    reward_variant: thaw_date
  torch:
    gpu: 0
    no_cuda: False
  train:
    dummy: base
    # override_name: Target
    train: True
    pretrain_frames: 1000 # 
    num_steps: 15000 #
    num_frames: 1000
    train_edge: fish Reward
    load_rollouts: /hdd/datasets/object_data/minibehavior/thawing/run/fish
    num_iters: 335
    batch_size: 128 # 
  critic_net:
  actor_net:
  network:
    activation_final: tanh
    scale_logits: 200
    hidden_sizes: 512
    net_type: mlp
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  extract:
    single_obs_setting: 0 1 0 1 0 0
    relative_obs_setting: 0 0 0 0 0
  option:
    term_form: reward
    term_as_done: True
    epsilon_close: 0.5
    param_norm: 1
    constant_lambda: 0
    true_lambda: 1
    inter_lambda: 0
    temporal_extend: 300
    time_cutoff: -1
    interaction_as_termination: False
  collect:
    buffer_len : 10000
    test_episode: True
    max_steps: 1000
    prioritized_replay: 0.2 0.4
    aggregator:
      sum_rewards: False
    stream_print_file: logs/minibehavior/final_stream.txt
    # display_param: 
  hindsight:
    use_her: False
    select_positive: 0.1
    max_hindsight: 20
    interaction_resample: False
    interaction_criteria: 1
    min_replay_len: 3
  policy:
    lookahead: 5
    learning_type: dqn
    tau: .001
    max_critic: 100
    epsilon_random: 0.1
    logging:
      log_interval: 10
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 5 #
      test_trials: 2 #
      max_terminate_step: 1 300
    learn:
      grad_epoch: 1
      sample_form: merged
  action:
    use_relative_action: False
    relative_action_ratio: 0.25
...