---
  record:
    # record_rollouts: ""
    record_recycle: -1
    # log_filename: /hdd/datasets/object_data/multi/randomdist/attn/small/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/all/breakout/attn/testrun/
    # save_dir: /nfs/data/calebc/object_data/all/randomdist/attn/default/
  environment:
    env: RandomDistribution
    # load_environment: /hdd/datasets/object_data/RandomDistribution/multi_random_small
    load_environment: /hdd/datasets/object_data/RandomDistribution/multi_passive_small/
    gym_to_gymnasium: False
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    # num_frames: 1000
    num_frames: 1000000
    # train_test_order: time
    # load_rollouts: /hdd/datasets/object_data/RandomDistribution/multi_random_small
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/multi_passive_small/
    num_iters: 40
    batch_size: 256
    # batch_size: 2
  multi_inter:
    evaluate: 2
    max_combination: 1
    dist_epsilon: 0.1
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/multi/randomcond/attn_np_small/temp/
    # save_intermediate: /hdd/datasets/object_data/multi/randomcond/attn_np_small/temp/
    # save_intermediate: /hdd/datasets/object_data/multi/randomcond/attn_small/temp/
    compare_trace: True
    proximity_epsilon: 7
    use_active_as_passive: True
    passive:
      passive_iters: 100000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
  full_inter:
    object_id: True
    lasso_lambda: 1 0 0 0 0
    dist_temperature: 5
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    log_gradients: True
    # train_full_only: True
    # train_names: phpt
  interaction_net:
    hidden_sizes: 256 512
    net_type: parattn
    init_form: xnorm # -1 dim is num_queries
    pair:
      final_layers: 256
      repeat_layers: True
    embed_inputs: 256
    # embed_inputs: 5
    mask_attn:
      # model_dim: 4 # 128
      # num_heads: 3 # 16
      model_dim: 128
      num_heads: 16
      num_layers: 3
      cluster: False
      num_clusters: 0
      attention_dropout: 0.3
      merge_function: cat
      gumbel_attention: -1
      append_keys: True
      no_hidden: True
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  EMFAC:
    # full_train: rxfbzvns
    full_train: ybb
    num_masks: 3
    E_step_iters: 100
    M_step_iters: 10
    refine_iters: 10
    binary_cost: 1
    model_mask_weights: 0.0 0.0 0.0
...