---
metaparam: 
  multi_filename: block_option_
  log_endpoint: ../datasets/object_data/robopushing/hyperparam/hyperparam_logs/block/net/
  yaml_endpoint: ../datasets/object_data/robopushing/hyperparam/hyperparam_yamls/block/net/
  save_endpoint: ../datasets/object_data/robopushing/hyperparam/hyperparam/block/net/
  graph_endpoint: ../datasets/object_data/robopushing/hyperparam/hyperparam_graphs/block/net/
  bash_path: bashes/block_net.sh
  base_config: configs/RoboPushing/gripper_block_option.yaml
  runfile: train_option.py
  gpu: 1
  match: False
train:
  num_iters: 3000
network:
  hidden_sizes: 128 128 128 128 128 128,512 512 512 512,1024 1024 1024
  activation_final: tanh
  scale_logits: 1,10
...