---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/attn/default/relaxed/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/small/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/attn/default/relaxed
  environment:
    env: RandomDistribution
    load_environment: /hdd/datasets/object_data/RandomDistribution/random/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random/
    num_iters: 1000
    batch_size: 64
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/attn/relaxed/temp/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/attn/relaxed/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 2000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 25
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 400
      intrain_passive: 1
      # weighting: 0 200000 100 100000
  full_inter:
    object_id: True
    lasso_lambda: 5 0.25 0 100 1000
    dist_temperature: 2
    mixed_interaction: relaxed
    soft_distribution: RelaxedBernoulli
    use_active_as_passive: True
    log_gradients: True
  interaction_net:
    # hidden_sizes: 128
    net_type: maskattn
    init_form: xnorm # -1 dim is num_queries
    pair:
      final_layers: 128
      repeat_layers: True
    mask_attn:
      model_dim: 128
      num_heads: 16
      num_layers: 2
      cluster: False
      num_clusters: 0
      attention_dropout: 0.1
      merge_function: cat
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.0001
...