---
  record:
    # record_rollouts: /nfs/data/calebc/object_data/breakout/testrun/paddle/
    # record_rollouts: /hdd/datasets/object_data/breakout/testrun/paddle
    record_recycle: -1
    log_filename: logs/temp/paddle_test.log
    load_dir: /hdd/datasets/object_data/breakout/testrun20
  environment:
    env: Breakout
    variant: drop_stopping
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action Paddle
    num_iters: 100
  collect:
    buffer_len : 100
    test_episode: True
    max_steps: 1000
    display_frame: 1
    save_display: /hdd/datasets/object_data/breakout/paddle_params/
  policy:
    logging:
      log_interval: 10
      test_log_maxlen: 50
      test_trials: 10
      max_terminate_step: 1 30
  sample:
    param_recycle: .5
...