---
  record:
    record_rollouts: ""
    record_recycle: -1
  environment:
    env: Breakout
    render: False
    frameskip: 1
    variant: default
    time_cutoff: -1
    seed: -1
    demonstrate: False
  torch:
    gpu: 0
    no_cuda: False
  train:
    num_frames: 1000
    train_edge: Action Paddle
    load_rollouts: /hdd/datasets/object_data/breakout/random
    train_iters: 20000
    batch_size: 64
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -16 -16 -1
    interaction_iters: 0
    load_intermediate: True
    save_intermediate: False
    compare_trace: True
    passive:
      passive_iters: 0
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      interaction_schedule: -1
      inline_iters: 5 1 1000
      interaction_weighting: -1 -1
    combined:
      weighting: -13, 1, 1, -1
  network:
    hidden_sizes: 256 256
    net_type: mlp
  optimizer:
    lr: .0001
    alt_lr: .0001
    eps: .00001
    alpha: 0.99
    betas: 0.9 0.999
    weight_decay: 0.00
...