---
  record:
    # record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/breakout/testrun/
    # save_dir: /nfs/data/calebc/object_data/breakout/testrun/
  environment:
    env: Breakout
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 50000
    train_test_order: time
    train_edge: Paddle Ball
    load_rollouts: /nfs/data/calebc/object_data/breakout/testrun/paddle/
    num_iters: 100000
    batch_size: 32
  inter:
    predict_dynamics: False
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: True
    save_intermediate: True
    compare_trace: True
    proximity_epsilon: 6
    passive:
      passive_iters: 30000
      passive_log_interval: 100
    active:
      active_log_interval: 100
      inline_iters: 10 1 10000
      interaction_weighting: 100 300000
      interaction_schedule: 10000
      weighting: -13 1 100 50000
  interaction_net:
    hidden_sizes: 128 128 128 128 128
    net_type: mlp
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...