---
  record:
    load_dir: /nfs/data/calebc/object_data/breakout/testrun/
    save_dir: /nfs/data/calebc/object_data/breakout/testrun/
  environment:
    env: Breakout
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Paddle Ball
    load_rollouts: /nfs/data/calebc/object_data/breakout/testrun/paddle/
    num_frames: 50000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.05
  inter:
    # save_intermediate: True
    load_intermediate: True
...