---
  record:
    load_dir: /hdd/datasets/object_data/breakout/testrun2
    save_dir: /hdd/datasets/object_data/breakout/testrun2
  environment:
    env: Breakout
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Paddle Ball
    load_rollouts: /hdd/datasets/object_data/breakout/testrun/paddle
    num_frames: 100000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.4 #0.05
    num_samples: 30
  inter:
    save_intermediate: True
    # load_intermediate: True
...