---
  record:
    # record_rollouts: ""
    log_dir: /nfs/data/calebc/object_data/breakout/testrun/ball_true_inter/
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/breakout/testrun/
    # save_dir: /nfs/data/calebc/object_data/breakout/testrun/
  environment:
    env: Breakout
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 300000
    train_test_ratio: .25
    train_test_order: time
    train_edge: Paddle Ball
    load_rollouts: /nfs/data/calebc/object_data/breakout/testrun/ball3/
    num_iters: 200000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/breakout/temp_ball/
    # save_intermediate: /hdd/datasets/object_data/breakout/temp_ball/
    compare_trace: True
    proximity_epsilon: 8
    passive:
      passive_iters: 100
      passive_log_interval: 100
    interaction:
      interaction_pretrain: 10000
    active:
    #   active_log_interval: 100
    #   inline_iters: 15 1 40000
    #   interaction_weighting: 100 -1
    #   interaction_schedule: 30000
      weighting: 0 200000 100 100000
      # error_binary_upweight: 5
      # intrain_passive: 1
  interaction_net:
    hidden_sizes: 128 128 128 128 128
    net_type: mlp
    optimizer:
      lr: .00005
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.0001
...
