---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /nfs/data/calebc/object_data/full/randomdist/conditional/selection/log/inter.log
    # load_dir: /nfs/data/calebc/object_data/full/breakout/selection/testrun/
    save_dir: /nfs/data/calebc/object_data/full/randomdist/conditional/selection/
  environment:
    env: RandomDistribution
    variant: conditional
    load_environment: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    load_rollouts: /hdd/datasets/object_data/RandomDistribution/random_conditional_long/
    num_iters: 100
    batch_size: 128
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/conditional/selection/temp2/
    save_intermediate: /hdd/datasets/object_data/full/randomdist/conditional/selection/temp2/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 3000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 1
      # inline_iters: 10 0 5000
      inline_iters: 200 0 0
      interaction_weighting: 1 -1
      interaction_schedule: -1
      intrain_passive: 0
      active_steps: 200
      # weighting: 0 1 1 1000
  full_inter:
    object_id: True
    lasso_lambda: 0 0 0 0 0
    dist_temperature: 2
    use_active_as_passive: True
    mixed_interaction: mixed
    soft_distribution: Identity
    log_gradients: True
    selection_mask: True
    # entropy_lambda: 5 0
    # train_names: phpt
  interaction_net:
    hidden_sizes: 512 512
    net_type: keypair
    init_form: xnorm
    embed_inputs: 128
    activation: leakyrelu
    cluster:
      num_clusters: 3
    pair:
      reduce_form: max
      num_layers: 1
    optimizer:
      lr: .0001
      alt_lr: .000002
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.0000
...