---
  record:
    record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/asteroids/testrun/
    save_dir: /nfs/data/calebc/object_data/asteroids/testrun/
  environment:
    env: Asteroids
    fixed_limits: True
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 10000
    train_edge: Action Ship
    load_rollouts: /hdd/datasets/object_data/asteroids/random/
    num_iters: 7500
    batch_size: 64
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -5 -5 -1
    interaction_iters: 0
    # load_intermediate: False
    # save_intermediate: True
    compare_trace: True
    passive:
      passive_iters: 30000
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      interaction_schedule: -1
      inline_iters: 5 1 1000
      interaction_weighting: -1 -1
    combined:
      weighting: -13 1 1 -1
  interaction_net:
    hidden_sizes: 128 128 128 128 512
    net_type: inexp
    activation_final: tanh
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...