---
  record:
    load_dir: /nfs/data/calebc/object_data/asteroids/testrun/
    save_dir: /nfs/data/calebc/object_data/asteroids/testrun/
    refresh: True
  environment:
    env: Asteroids
    variant: default
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action Ship
    load_rollouts: /hdd/datasets/object_data/asteroids/random
    num_frames: 1000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.01
...