---
  record:
    # record_rollouts: /hdd/datasets/calebc/object_data/asteroids/ship/
    # record_recycle: -1
    log_filename: logs/temp/laser_train.log
    load_dir: /nfs/data/calebc/object_data/asteroids/testrun_laser/
    # save_dir: /nfs/data/calebc/object_data/asteroids/testrun_laser/
    checkpoint_dir: /nfs/data/calebc/object_data/asteroids/testrun/ship_laser_checkpoint
    # load_checkpoint: /nfs/data/calebc/object_data/breakout/testrun_inline/action_paddle_checkpoint
    # presave_graph: True
    save_interval: 100
  environment:
    env: Asteroids
    variant: default
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_steps: 100
    pretrain_frames: 30000
    load_rollouts: /hdd/datasets/object_data/asteroids/random
    train_edge: Ship Action Laser
    num_iters: 5000
    batch_size: 256
  critic_net:
  actor_net:
  network:
    hidden_sizes: 512 512 512 512
    net_type: basic
    activation_final: tanh
    scale_logits: 50
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
    pair:
      final_layers: 512
  sample:
    sample_type: angle
    sample_distance: 0.2
    sample_schedule: 400
    param_recycle: 0.1
  extract:
    single_obs_setting: 1 1 0 1 0 0
    relative_obs_setting: 0 0 1 0
  option:
    term_form: combined
    dummy_interaction: laser
    sample_parent: True
    term_as_done: True
    epsilon_close: 2 2 0.3 0.3 0.5
    param_norm: 1
    constant_lambda: -1
    param_lambda: 1
    inter_lambda: 0
    temporal_extend: 10
    time_cutoff: 50
  collect:
    prioritized_replay: 0.4 0.4
    buffer_len : 100000
    test_episode: True
    max_steps: 1000
    stream_print_file: logs/asteroids/hyperparam/laser_option_stream.txt
  hindsight:
    use_her: True
    early_stopping: 2
    interaction_criteria: 1
  policy:
    epsilon_random: 0.2
    learning_type: ddpg
    ground_truth: Ship
    logging:
      log_interval: 100
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 20
      test_trials: 10
      max_terminate_step: 1 50
    learn:
      post_random_iters: 250
      grad_epoch: 200
      sample_form: merged
  action:
    use_relative_action: True
    relative_action_ratio: 0.3
...