---
  record:
    load_dir: /nfs/data/calebc/object_data/breakout/fixed_limits/testrun
    save_dir: /nfs/data/calebc/object_data/breakout/fixed_limits/testrun
    refresh: True
  environment:
    env: Breakout
    variant: default
    fixed_limits: True
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action Paddle
    load_rollouts: /hdd/datasets/object_data/breakout/fixed_limits/random/
    num_frames: 1000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.03
...