---
metaparam: 
  multi_filename: ship_option_
  log_endpoint: /hdd/datasets/object_data/asteroids/hyperparam/hyperparam_logs/ship/tc2/
  yaml_endpoint: /hdd/datasets/object_data/asteroids/hyperparam/hyperparam_yamls/ship/tc2/
  save_endpoint: /hdd/datasets/object_data/asteroids/hyperparam/hyperparam/ship/tc2/
  graph_endpoint: /hdd/datasets/object_data/asteroids/hyperparam/hyperparam_graphs/ship/tc2/
  bash_path: ship_tc2.sh
  base_config: configs/Asteroids/rotation/action_ship_option.yaml
  runfile: train_option.py
  gpu: 2
  match: True
option:
  time_cutoff: 20,30,50,75,100
policy:
  max_min_critic: -20 0,-30 0,-50 0,-75 0,-100 0
  rainbow:
    num_atoms: 51,51,51,75,100
...
