---
  record:
    # record_rollouts: ""
    record_recycle: -1
    # log_filename: /hdd/datasets/object_data/full/Breakout/rand_tiny/base/log/inter.log
    # # load_dir: /hdd/datasets/object_data/full/Breakout/rand_tiny/testrun/
    # save_dir: /hdd/datasets/object_data/full/Breakout/rand_tiny/base/
    # log_filename: /data/calebc/object_data/full/Breakout/rand_tiny/base/log/inter.log
    # # load_dir: /data/calebc/object_data/full/Breakout/rand_tiny/testrun/
    # save_dir: /data/calebc/object_data/full/Breakout/rand_tiny/base/
    log_filename: /mnt/Data/calebc/object_data/full/Breakout/rand_tiny/base/log/inter.log
    # load_dir: /mnt/Data/calebc/object_data/full/Breakout/rand_tiny/testrun/
    save_dir: /mnt/Data/calebc/object_data/full/Breakout/rand_tiny/base/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/rand_tiny/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/Breakout/rand_tiny/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/Breakout/rand_tiny/base/
  environment:
    env: Breakout
    variant: rand_tiny
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/RandomBreakout/rand_tiny/
    # load_environment: /hdd/datasets/object_data/Breakout/rand_tiny/
    # load_environment: /data/calebc/object_data/Breakout/rand_tiny/
    load_environment: /mnt/Data/calebc/object_data/Breakout/rand_tiny/
  collect:
    omit_done: True
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 500000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/RandomBreakout/rand_tiny/
    # load_rollouts: /hdd/datasets/object_data/Breakout/rand_tiny/
    # load_rollouts: /data/calebc/object_data/Breakout/rand_tiny/
    load_rollouts: /mnt/Data/calebc/object_data/Breakout/rand_tiny/
    num_iters: 60000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    load_intermediate: /mnt/Data/calebc/object_data/full/Breakout/rand_tiny/base/temp/
    # save_intermediate: /data/calebc/object_data/full/Breakout/rand_tiny/base/temp/
    # save_intermediate: /mnt/Data/calebc/object_data/full/Breakout/rand_tiny/base/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 1500
      # passive_iters: 100
      passive_log_interval: 100
      # pretrain_active: True
    active:
      active_log_interval: 200
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 2 -1
      interaction_schedule: 20000
      weighting: 0 200000 2.5 -1
      # intrain_passive: 1
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    # use_active_as_passive: True
    train_names: Ball
    adaptive_lasso: 2 1
    adaptive_lasso_bias: 3 -1
    reset_caloss: True
    delay_inter_train: 5000
  interaction_net:
    hidden_sizes: 256 256 256 256 256
    net_type: keypair
    init_form: xnorm
    embed_inputs: 1024
    # activation: crelu
    pair:
      reduce_function: sum
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.000
...