---
  alter_base: configs/full_training/Breakout/base.yaml
  torch:
    gpu: 1
  inter:
    interaction:
      interaction_pretrain: 20000
      soft_train: 0.15
  full_inter:
    selection_train: proximity
...