---
metaparam: 
  multi_filename: base_opt_
  log_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_logs/base_tests/test/
  yaml_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_yamls/base_tests/test/
  save_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam/base_tests/test/
  graph_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_graphs/base_tests/test/
  bash_path: bashes/base_full_runs.sh
  base_config: configs/full_training/RandomDistribution/full_random_relaxed_distribution.yaml
  runfile: train_full_interaction.py
  gpu: 4
  match: 1
  simul_run: 4
  num_trials: 2
  cycle_gpu: 4
full_inter:
  mixed_interaction: relaxed,mixed,hard,weighting
  soft_distribution: RelaxedBernoulli,Identity,Identity,Identity
...