---
  record:
    # record_rollouts: ""
    record_recycle: -1
    # log_filename: /hdd/datasets/object_data/full/Pusher2D/tiny/base/log/inter.log
    # # load_dir: /hdd/datasets/object_data/full/Pusher2D/tiny/testrun/
    # save_dir: /hdd/datasets/object_data/full/Pusher2D/tiny/base/
    log_filename: /data/calebc/object_data/full/Pusher2D/tiny/base/log/inter.log
    # load_dir: /data/calebc/object_data/full/Pusher2D/tiny/testrun/
    save_dir: /data/calebc/object_data/full/Pusher2D/tiny/base/
    # log_filename:  /work/pi_sniekum_umass_edu/calebc/object_data/tiny/log/inter.log
    # # load_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/Pusher2D/tiny/testrun/
    # save_dir:  /work/pi_sniekum_umass_edu/calebc/object_data/full/Pusher2D/tiny/base/
  environment:
    env: Pusher2D
    variant: tiny
    # load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/Pusher2D/rand_greedy_sticky/
    # load_environment: /hdd/datasets/object_data/Pusher2D/rand_greedy_sticky/
    load_environment: /data/calebc/object_data/Pusher2D/rand_tiny/
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_frames: 500000
    train_test_order: time
    # load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/Pusher2D/rand_greedy_sticky/
    # load_rollouts: /hdd/datasets/object_data/Pusher2D/rand_greedy_sticky/
    load_rollouts: /data/calebc/object_data/Pusher2D/rand_tiny/
    num_iters: 50000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    load_intermediate: /hdd/datasets/object_data/full/Pusher2D/tiny/base/temp/
    # save_intermediate: /data/calebc/object_data/full/Pusher2D/tiny/base/temp/
    compare_trace: True
    proximity_epsilon: 2.0
    passive:
      passive_iters: 5000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 200
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 5000
      # weighting: 0 200000 1 -1
      intrain_passive: 1
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: Block
    adaptive_lasso: 1 1
    delay_inter_train: 1000
  interaction_net:
    hidden_sizes: 256 256 256
    net_type: keypair
    init_form: xnorm
    embed_inputs: 512
    activation: crelu
    pair:
      reduce_function: sum
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.000
...