---
  metaparam: 
    multi_filename: cond_base_opt_
    log_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_logs/selection/cond/
    yaml_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_yamls/selection/cond/
    save_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam/selection/cond/
    graph_endpoint: /nfs/data/calebc/object_data/full/hyperparam/hyperparam_graphs/selection/cond/
    bash_path: bashes/selection_cond_runs.sh
    base_config: configs/full_training/RandomDistribution/conditional/selection/selection_relaxed.yaml
    runfile: train_full_interaction.py
    gpu: 1
    match: 1
    simul_run: 4
    num_trials: 1
    cycle_gpu: 4
  full_inter:
    mixed_interaction: relaxed,mixed,hard,weighting
    soft_distribution: RelaxedBernoulli,Identity,Identity,Identity
...