---
  record:
    # record_rollouts: /nfs/data/calebc/object_data/breakout/testrun/paddle/
    record_rollouts: /nfs/data/object_data/robopush/testrun/gripper
    record_recycle: -1
    log_filename: logs/temp/gripper_train
    load_dir: /nfs/data/object_data/robopush/testrun
    save_dir: /nfs/data/object_data/robopush/testrun
    # checkpoint_dir: /hdd/datasets/object_data/robopush/testrun/action_gripper_checkpoint
    record_graphs: /nfs/data/object_data/robopush/testrun/gripper_graphs
    # pretrain_dir: /hdd/datasets/object_data/robopushing/testrun/action_gripper_checkpoint
    save_interval: 100
  environment:
    env: RoboPushing
    variant: default
    time_cutoff: 200
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    pretrain_frames: 3000
    num_steps: 90
    num_frames: 1000
    train_edge: Action Gripper
    load_rollouts: /nfs/data/object_data/robopush/random
    num_iters: 1200
    batch_size: 64
  critic_net:
  actor_net:
  network:
    hidden_sizes: 256 256
    net_type: mlp
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  sample:
    sample_type: cent
    sample_distance: 0.3
    sample_schedule: 200
    param_recycle: 0.1
  extract:
    single_obs_setting: 1 0 0 1 0 0
    relative_obs_setting: 0 0 0 0 1
  option:
    term_form: param
    term_as_done: True
    epsilon_close: .003
    param_norm: 3
    constant_lambda: -1
    param_lambda: 1
    inter_lambda: 0
    temporal_extend: 10
    time_cutoff: 30
  collect:
    buffer_len : 100000
    test_episode: True
    max_steps: 1000
    stream_print_file: logs/robo/ag_option_stream.txt
    time_check: True
  hindsight:
    use_her: True
  policy:
    learning_type: ddpg
    epsilon_random: 0.01
    logging:
      log_interval: 10
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 20
      test_trials: 10
      max_terminate_step: 1 30
    learn:
      grad_epoch: 100
      sample_form: merged
...