---
  record:
    load_dir: /nfs/data/object_data/robopush/testrun
    save_dir: /nfs/data/object_data/robopush/testrun
    refresh: True
  environment:
    env: RoboPushing
    variant: default
  torch:
    gpu: 1
    no_cuda: False
  train:
    train_edge: Action Gripper
    load_rollouts: /nfs/data/object_data/robopush/random
    num_frames: 10000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.05
    sample_grid: False
...