---
  record:
    record_rollouts: ""
    record_recycle: -1
    # load_dir: /nfs/data/calebc/object_data/robopushing/testrun/
    save_dir: /nfs/data/calebc/object_data/robopushing/testrun/
  environment:
    env: RoboPushing
  torch:
    gpu: 1
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_edge: Gripper Action Block
    load_rollouts: /hdd/datasets/object_data/robopushing/testrun/gripper
    num_iters: 50000
    batch_size: 128
  inter:
    predict_dynamics: True
    interaction_testing: 0.5 -1 -1 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/temp/
    save_intermediate: /hdd/datasets/object_data/temp/
    compare_trace: True
    passive:
      passive_iters: 10000
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 100
      interaction_schedule: -1
      inline_iters: 5 1 1000
      interaction_weighting: -1 -1
      weighting: 0 200000 100 100000
  interaction_net:
    hidden_sizes: 512 512 512
    net_type: mlp
    optimizer:
      lr: .0001
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
...