---
  record:
    load_dir: /nfs/data/object_data/robopush/testrun
    save_dir: /nfs/data/object_data/robopush/testrun
  environment:
    env: RoboPushing
    variant: default
  torch:
    gpu: 1
    no_cuda: False
  train:
    train_edge: Gripper Action Block
    load_rollouts: /nfs/data/object_data/robopush/testrun/gripper
    num_frames: 30000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.15
    num_samples: 60
    sample_grid: False
    dynamics_difference: True
...