---
  record:
    # record_rollouts: /nfs/data/calebc/object_data/breakout/testrun/ball/
    # record_rollouts: /hdd/datasets/object_data/breakout/testrun/ball
    record_recycle: -1
    log_filename: logs/temp/big_block_train.log
    load_dir: /nfs/data/calebc/object_data/breakout/testrun_inline/
    save_dir: /nfs/data/calebc/object_data/breakout/big_block/
    # checkpoint_dir: /nfs/data/calebc/object_data/breakout/testrun/paddle_ball_checkpoint
    save_interval: 100 #
  environment:
    env: RoboPushing
    variant: obstacles_many
    render: True
  torch:
    gpu: 0
    no_cuda: False
  train:
    dummy: True
    train: True
    pretrain_frames: 10000 # 
    num_steps: 300 #
    num_frames: 1000
    train_edge: Block Obstacle Target
    load_rollouts: /hdd/datasets/object_data/breakout/ball
    num_iters: 3000
    batch_size: 128 # 
  critic_net:
  actor_net:
  network:
    hidden_sizes: 128 128 128 256 1024
    net_type: pair
    activation_final: tanh
    scale_logits: 1
    optimizer:
      lr: .00003
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  sample:
    sample_type: exist
    param_recycle: 0.1
  extract:
    single_obs_setting: 1 1 1 0 0 0
    relative_obs_setting: 0 0 1 0
  option:
    term_form: param
    term_as_done: True
    epsilon_close: 0.05
    param_norm: 2
    constant_lambda: 0
    true_lambda: 1
    param_lambda: 1
    inter_lambda: 1
    temporal_extend: 10
    time_cutoff: -1
  collect:
    buffer_len : 10000
    test_episode: True
    max_steps: 1000
    prioritized_replay: 0.2 0.4
    aggregator:
      sum_rewards: False
  stream_print_file: logs/robo/final_stream.txt
  hindsight:
    use_her: True
    select_positive: 0.2
    max_hindsight: 20
    interaction_resample: False
    interaction_criteria: 1
    min_replay_len: 1
  policy:
    lookahead: 5
    learning_type: sac
    tau: .001
    max_critic: 200
    epsilon_random: 0.1
    logging:
      log_interval: 50
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 20 #
      test_trials: 10 #
      max_terminate_step: 1 300
    learn:
      grad_epoch: 300
      sample_form: merged
  action:
    use_relative_action: True
    relative_action_ratio: 0.07
...