---
  record:
    load_dir: /nfs/data/calebc/object_data/asteroids/coordinate_turn/testrun/
    save_dir: /nfs/data/calebc/object_data/asteroids/coordinate_turn/testrun/
    refresh: True
  environment:
    env: Asteroids
    variant: coordinate_turn
    fixed_limits: True
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action Ship
    load_rollouts: /hdd/datasets/object_data/asteroids/coordinate_turn/random
    num_frames: 1000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.03
...