---
  record:
    record_rollouts: /hdd/datasets/calebc/object_data/asteroids/coordinate_turn/ship/
    record_recycle: -1
    log_filename: logs/temp/ship_coord_train.log
    load_dir: /nfs/data/calebc/object_data/asteroids/coordinate_turn/testrun/
    save_dir: /nfs/data/calebc/object_data/asteroids/coordinate_turn/testrun/
    # checkpoint_dir: /nfs/data/calebc/object_data/breakout/testrun/action_paddle_checkpoint
    # load_checkpoint: /nfs/data/calebc/object_data/breakout/testrun_inline/action_paddle_checkpoint
    save_interval: 100
  environment:
    env: Asteroids
    variant: coordinate_turn
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_steps: 100
    pretrain_frames: 10000
    load_rollouts: /hdd/datasets/object_data/asteroids/coordinate_turn/random
    train_edge: Action Ship
    num_iters: 7000
    batch_size: 64
  critic_net:
  actor_net:
  network:
    hidden_sizes: 128 128 128 512 512
    net_type: basic
    activation_final: tanh
    scale_logits: 50
    optimizer:
      lr: .0003
      alt_lr: .0001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.00
  sample:
    sample_type: angle
    sample_distance: 0.2
    sample_schedule: 400
    param_recycle: 0.1
  extract:
    single_obs_setting: 1 0 0 1 0 0
    relative_obs_setting: 0 0 0 1
  option:
    term_form: param
    term_as_done: True
    epsilon_close: 1 1 0.5 0.5 0.5
    param_norm: 1
    constant_lambda: -1
    param_lambda: 1
    inter_lambda: 0
    temporal_extend: 20
    time_cutoff: 50
  collect:
    prioritized_replay: 0.6 0.4
    buffer_len : 500000
    test_episode: True
    max_steps: 1000
    stream_print_file: logs/asteroids/ct_ship_option_stream.txt
  hindsight:
    use_her: True
    early_stopping: 3
  policy:
    epsilon_random: 0.1
    logging:
      log_interval: 100
      train_log_maxlen: 5
      test_log_maxlen: 50
      initial_trials: 20
      test_trials: 10
      max_terminate_step: 1 30
    learn:
      grad_epoch: 200
      sample_form: merged
...