---
  record:
    load_dir: /hdd/datasets/object_data/minibehavior/installing_printer/run
    save_dir: /hdd/datasets/object_data/minibehavior/installing_printer/run
    refresh: True
  environment:
    env: MiniBehavior
    variant: installing_printer
  torch:
    gpu: 0
    no_cuda: False
  train:
    train_edge: Action agent
    load_rollouts: /hdd/datasets/object_data/minibehavior/installing_printer/random
    num_frames: 10000
  mask:
    min_sample_difference: 0.1
    var_cutoff: 0.001
...