---
  record:
    # record_rollouts: ""
    record_recycle: -1
    log_filename: /hdd/datasets/object_data/full/randomdist/conditional_passive/mixed/log/inter.log
    # load_dir: /hdd/datasets/object_data/full/breakout/mixed/testrun/
    save_dir: /hdd/datasets/object_data/full/randomdist/conditional_passive/mixed/
  environment:
    env: RandomDistribution
    variant: conditional_passive
    load_environment: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDistribution/random_conditional_passive/
  torch:
    gpu: 0
    no_cuda: False
  train:
    train: True
    num_frames: 100000
    train_test_order: time
    load_rollouts: /work/pi_sniekum_umass_edu/calebc/object_data/RandomDistribution/random_conditional_passive/
    num_iters: 50000
    batch_size: 512
  inter:
    predict_dynamics: True
    interaction_testing: 0.9 -1 -10 -1
    interaction_iters: 0
    # load_intermediate: /hdd/datasets/object_data/full/randomdist/conditional_passive/mixed/temp/
    # save_intermediate: /hdd/datasets/object_data/full/randomdist/conditional_passive/mixed/temp/
    compare_trace: True
    proximity_epsilon: 7
    passive:
      passive_iters: 3000
      # passive_iters: 100
      passive_log_interval: 100
      pretrain_active: True
    active:
      active_log_interval: 500
      # inline_iters: 10 0 5000
      inline_iters: 1 0 0
      interaction_weighting: 100 -1
      interaction_schedule: 10000
      # weighting: 0 200000 100 100000
      intrain_passive: 1
  full_inter:
    object_id: True
    lasso_lambda: 3 0 0 0 1000
    mixed_interaction: mixed
    soft_distribution: Identity
    use_active_as_passive: True
    train_names: hlodufryk
    adaptive_lasso: 7
  interaction_net:
    hidden_sizes: 256 256 256
    net_type: keypair
    init_form: xnorm
    activation: leakyrelu
    embed_inputs: 512
    pair:
      reduce_function: sum
    optimizer:
      lr: .0001
      alt_lr: .00001
      eps: .00001
      alpha: 0.99
      betas: 0.9 0.999
      weight_decay: 0.0
...